platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Canvas' do
 # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 # use_frameworks!

 # Pods for Canvas

 pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'Core',
   'CxxBridge',
   'DevSupport',
   'RCTText',
   'RCTNetwork',
   'RCTWebSocket',
   'RCTAnimation',
   'RCTImage',
 ]

 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
 pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
 pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
 pod 'FacebookSDK', '~> 4.38.0'
 pod 'FBSDKShareKit', '~> 4.38.0'
 pod 'FBSDKCoreKit', '~> 4.38.0'
 pod 'FBSDKLoginKit', '~> 4.38.0'
 pod 'GoogleSignIn', '~> 4.4.0'


 use_unimodules!

 pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

 pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

 pod 'RNFS', :path => '../node_modules/react-native-fs'
 pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

 pod 'RNSound', :path => '../node_modules/react-native-sound'
 pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

 post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

 target 'CanvasTests' do
   inherit! :search_paths
   # Pods for testing
 end

end

target 'Canvas-tvOS' do
 # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 # use_frameworks!

 # Pods for Canvas-tvOS

 target 'Canvas-tvOSTests' do
   inherit! :search_paths
   # Pods for testing
 end

end
