platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Canvas' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Canvas

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!

  target 'CanvasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Canvas-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Canvas-tvOS

  target 'Canvas-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
