# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do 
   ENV["SLACK_URL"] ||=https://hooks.slack.com/services/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

  end

  lane :tests do
    run_tests(scheme: "MyAppTests")
  end

  lane :screenshots do
  desc "Capturing screenshots to upload"
    capture_screenshots
    frame_screenshots(white: true)
    upload_to_app_store
  end

  lane :beta do
    desc "initialing beta test"
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app
    increment_build_number
    upload_to_testflight
    slack(message: "Successfully distributed a new beta build")
  end

  lane :release do
    capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app
    increment_build_number
    upload_to_app_store                  # upload your app to App Store Connect
    slack(message: "Successfully uploaded a new App Store build")
  end

end

